### ISSUE TITLE
make it more obvious that SourceGraph is what to look at to do the review

### ISSUE THREAD

**Issue by Gankra** [axodotdev/harbor#15]
Right now it's not obvious what SourceGraph is, and its position in the top-right feels a bit de-emphasized. I'm not really sure what the Ideal design is, but it should probably more loudly scream "this is the button to do the review!!!".

For reference, the ostensible workflow of a user would be:

1. Open the report
2. Click on a library they want to review
3. Check what criteria they need to review it for (maybe review the definitions, maybe just remember them)
4. Click on SourceGraph
5. Review The Code
6. Come back to the UI
7. Sign off on all the EULAs
8. Maybe add some notes
9. GOTO 2
10. Click Commit When Satisfied

**Comment by SaraVieira** [comment]
Has been fixed :D
