### ISSUE TITLE
Make baseline responsive

### ISSUE THREAD

**Issue by sarahghp** [axodotdev/harbor#35]
When working on https://github.com/axodotdev/harbor/pull/33 I noticed that some baseline responsiveness is missing here. These are the two big things that should be fixed.

## Text Line-Breaks
<img width="1550" alt="Screen Shot 2022-11-15 at 11 55 47 AM" src="https://user-images.githubusercontent.com/1477362/202451182-044964f0-d0d4-438c-a9fe-36796d8ed39d.png">

The text is being ingested with fixed line-breaks. We should find out why and not do that. We can either stop them where they are coming in and leave `white-space-pre-wrap` for paragraph breaks, _or_ we can find a way to break out the paragraphs and wrap each in a `p` and then the internal line-breaks will be ignored.

## Mobile Size CSS

This is how it currently looks. I would probably come up with something so that the sidebar is a separate layout that is navigated to, but one could also use something similar to the header list and let users pick an item from that. I don't have a real vision but it seems like we should do something.

<img width="562" alt="Screen Shot 2022-11-17 at 1 54 33 PM" src="https://user-images.githubusercontent.com/1477362/202451934-f787f367-59da-48ec-bdd3-922fa91916db.png">

**Comment by sarahghp** [comment]
@sarahghp @ashleygwilliams @Gankra I have put this in as an MVP because Harbor is not currently usable on a phone. If you think our primary user will be ok not using it on a phone at the first, we could also replace the functionality at smaller sizes with a note encouraging computer use and call it good to start. It's up to you, but I've at least captured the state for now here.

**Comment by ashleygwilliams** [comment]
i think for MVP a mobile view is not required- in the long run- reviewing dependency source code on your phone is something folks could theoretically do but i think in practice it would not be the norm and that just focusing on a single desktop view is the right call for the moment. i do think it would be worthwhile to fail gracefully, but anything else would be out of scope imo

**Comment by sarahghp** [comment]
Okay, that sounds good. @SaraVieira if we add a graceful degradation that says "use me on a desktop" I think that would be good. (And if the line length thing is easy to fix, that too.)

**Comment by sarahghp** [comment]
Based on discussion, for the text, we should use a package and interpret it as markdown. Issue here: https://github.com/axodotdev/harbor/issues/36
